var user = {
	MIN_PASSWORD_LENGTH: 7, // MINIMUM LENGTH ON USER PASSWORDS
	USER_TOKENS: {
		RESET_PASSWORD_TOKEN_EXPIRATIONTIME: 60 * 60 * 1000, 	// MILLISECONDS
		UPDATE_EMAIL_TOKEN_EXPIRATIONTME: 60 * 60 * 1000, 		// MILLISECONDS
		CONFIRM_EMAIL_TOKEN_EXPIRATIONTIME: 60 * 60 * 1000 		// MILLISECONDS
	}
};

module.exports = user;
